language: python
python:
  - "3.8"
install:
  - make install
  - pip install -r requirements_test.txt

before_script:
  - make verify-lint
script:
  - make test

deploy:
  provider: pypi
  username: "__token__"
  password: "pypi-AgEIcHlwaS5vcmcCJDk2ZmY4YWNiLTZmNDgtNDA4Ni1hZDE4LWRkZDA5NGVhNTFkOQACOnsicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJyb2NrZXQtcHkiXX0sICJ2ZXJzaW9uIjogMX0AAAYgfHEYb5bppuxoyyXJkJ4cozz4NaAwRTvUKiGBxr0MN9c"
  on:
    all_branches: true
    python: 3.8
